# Generated by Django 4.1.7 on 2023-06-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "cou_name",
                    models.CharField(
                        max_length=60, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("cou_building", models.CharField(max_length=60)),
                ("cou_room", models.CharField(max_length=60)),
                (
                    "cou_term",
                    models.CharField(
                        choices=[
                            ("1 Year", "1 Year"),
                            ("2 Years", "2 Years"),
                            ("3 Years", "3 Years"),
                            ("4 Years", "4 Years"),
                        ],
                        default="2 Years",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "stu_name",
                    models.CharField(
                        max_length=60, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("stu_dob", models.DateField(max_length=60)),
                ("stu_email", models.CharField(max_length=60)),
                ("stu_phone", models.CharField(max_length=60)),
                ("stu_address", models.CharField(max_length=60)),
                ("stu_city", models.CharField(max_length=60)),
                ("stu_postcode", models.CharField(max_length=60)),
                (
                    "stu_term",
                    models.CharField(
                        choices=[
                            ("1st Year", "1st Year"),
                            ("2nd Year", "2nd Year"),
                            ("3rd Year", "3rd Year"),
                            ("4th Year", "4th Year"),
                        ],
                        default="2nd Year",
                        max_length=10,
                    ),
                ),
                (
                    "stu_course",
                    models.ForeignKey(
                        db_column="cou_name",
                        max_length=60,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
            },
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "lec_name",
                    models.CharField(
                        max_length=60, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("lec_dob", models.DateField(max_length=60)),
                ("lec_email", models.CharField(max_length=60)),
                ("lec_phone", models.CharField(max_length=60)),
                ("lec_address", models.CharField(max_length=60)),
                ("lec_city", models.CharField(max_length=60)),
                ("lec_postcode", models.CharField(max_length=60)),
                (
                    "lec_course",
                    models.ForeignKey(
                        db_column="cou_name",
                        max_length=60,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecturer",
            },
        ),
    ]
